services:
  - type: web
    name: pergunte-ia
    runtime: python
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false